show_subscribe_button:
  type: bool
  default: true
  description:
    en: "Display the Subscribe button on the Upcoming Events page."

subscribe_button_icon:
  type: string
  default: "square-check"
  description:
    en: "Font Awesome icon name for the Subscribe button. Leave blank for no icon."

new_event_url:
  type: string
  default: ""
  description:
    en: "URL for the New event button. Leave blank to hide the New event button."

new_event_button_icon:
  type: string
  default: "calendar-plus"
  description:
    en: "Font Awesome icon name for the New event button. Leave blank for no icon."

hide_expired_yearly_view:
  type: bool
  default: true
  description:
    en: "Hide past days and past events in the yearly list view."
